version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - run:
          command: make lint
          name: Lint
      - restore_cache:
          keys:
            - udacity-micrervices-deps-{{ checksum "requirements.txt" }}
      # - run:
      #     command: make install
      #     name: install depedencies
      # - python/install-deps
      # - python/save-cache

workflows:
  main:
    jobs:
      - build
