version: 2.1

jobs:
  build:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - udacity-micrervices-deps-{{ checksum "requirements.txt" }}
            - hadolint
      - run:
          command: make install
          name: install depedencies
      - run:
          name: Get hadolint
          command: bash ci/download-hadolint.sh
      - run:
          name: Lint
          command: make lint
      - save_cache:
          key: udacity-micrervices-deps-{{ checksum "requirements.txt" }}
          paths:
            - venv
      - save_cache:
          key: hadolint
          paths:
            - ci/hadolint
      # - python/install-deps
      # - python/save-cache

workflows:
  main:
    jobs:
      - build
